### ISSUE TITLE
Kubernetes version 1.22 and above does not support "networking.gke.io/v1alpha2"

### ISSUE THREAD

**Issue by Cessaa** [GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang#20]
Hello,

We love this project and enjoy using it very much but can't use the project since we upgraded k8s version to 1.22.6.
As it is written here, the use of v1alpha2 has disappeared.
[deprecation-guide/v1-22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22)

We made the changes in the manifest files, but it was not enough. I guess the source code needs to be updated. 

Can you improve on this?
How can we use this project in new k8s versions?
![github-issue](https://user-images.githubusercontent.com/57228637/173776451-0ec909a9-27cb-4237-a03f-b29a67271949.PNG)

**Comment by MrTrustor** [comment]
Hi,

This is just to acknowledge that we've seen this issue. We are discussing internally how to proceed and will report back here.

Thanks,

**Comment by Cessaa** [comment]
I look forward to your improvements.

Thanks,

**Comment by mertomert** [comment]
Hello,
I am experiencing the same problem. Do you have a solution suggestion, can you please share?

Thanks,

**Comment by laurentgrangeau** [comment]
Hi,
I'm working on a fix and will update you.
Thanks,

**Comment by Cessaa** [comment]
Is there any improvement? I'm waiting for good news from you.

Thanks,

**Comment by suleymanbyzt** [comment]
i'm having the same problem. Can you share a solution suggestion about the issue?

**Comment by polarbit** [comment]
Hi, we face the same issue. Looking forward the fix here.

**Comment by selmanahatli** [comment]
Hi,
I am suffering because of same issue. I am waiting for the fix too

**Comment by onuyanik** [comment]
We also have the same issue. Is there any progress on the fix?

**Comment by mozartwalkingaround** [comment]
Hi,

I'm also waiting for this fix. 

Thanks

**Comment by suleymanbyzt** [comment]
Please let me know if there are any developments.

Thanks.

**Comment by suleymanbyzt** [comment]
Please let me know if there are any improvements.

Thanks.

**Comment by MrTrustor** [comment]
Hi everyone,

You don't need to comment here. If you want to show that you are impacted, please add a reaction to the initial post on this issue.
We're still working on a fix.

Thank you for understanding

**Comment by MrTrustor** [comment]
Hi everyone, @laurentgrangeau is nearing a solution in #21. If you're willing to do some testing and give some feedback, feel free to do so on the PR itself (you'll need to compile the project yourself though).

**Comment by Cessaa** [comment]
Hi MrTrustor, I tried it and wrote my review, thanks
