### ISSUE TITLE
AAAA lookup feature toggle

### ISSUE THREAD

**Issue by k11h-de** [GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang#24]
Hi,

first off: Thanks a million for your effort and invested time :partying_face:

For us this is a quite helpful piece of software.
We're running version `0.3-rc1 release` in our *v1.23.4* K8s cluster and noticed a "bug" on our end. 
As our cloud providers implementation of network policies do not support IPv6 ([docs](https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_0059.html)) - everything is working as expected when a FQDN resolves only to A records but all outgoing traffic is denied once there is a single AAAA record in the generated NetworkPolicy. 
Again, this is a limitation in our cloud providers implementation, but this cannot be changed easily.

Now the question: do you see any chance to add a parameter to enable/disable AAAA lookups. I know support for AAAA was only added recently. I looked at the code and have not found any toggle to enable or disable this feature.

Unfortunately, I am *only* a DevOps guy, with very little golang knowhow.

Thanks a lot again.
Karsten

**Comment by MrTrustor** [comment]
Hi Karsten,

I can confirm that there is no support for disabling AAAA lookups. Unfortunately, we have very limited resources to dedicate to this project, and we will not be able to make changes to support another Kubernetes service beyond GKE. However, you (or anyone else) is welcomed to contribute. The most straightforward way to do this would be to add a new annotation.

Please let me know if this is something you would like to work on yourself, and I can provide a bit more guidance.

**Comment by k11h-de** [comment]
Hey Théo, 

I totally understand and we're already very grateful you shared the code. This is a good opportunity for me to get some coding experience. I will try to set up a working development environment as per your docs. 
And I totally agree that adding another annotation is a good approach - I'll try my best.

Cheers Karsten

**Comment by k11h-de** [comment]
Hi Théo,

your documentation on how to set up a development environment is brilliant. Thanks to that I was able to contribute the required change. I hope it meets your minimum requirements for a PR.

Thanks for your feedback
Karsten

**Comment by MrTrustor** [comment]
Thank you for your contribution! I published [0.3-rc2@](https://github.com/GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang/releases/tag/0.3-rc2). Let me know if you have any problems with it. If don't hear anything from anyone by the end of next week (more or less), I'll probably promote it to the full 0.3 release.

**Comment by k11h-de** [comment]
Perfect, thanks a million for your support.
